# Generated by Django 4.1.7 on 2023-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_theme_slug_alter_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Тема билета'),
        ),
    ]
