# Generated by Django 4.1.7 on 2023-03-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(db_index=True, default=1, null=True, verbose_name='Билет'),
        ),
    ]
