# Generated by Django 4.1.7 on 2023-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ticket_name_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
