# Generated by Django 4.1.7 on 2023-03-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_answer_text_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.theme'),
        ),
    ]
