# Generated by Django 4.1.7 on 2023-03-23 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_question_theme_alter_question_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.theme'),
        ),
    ]
