# Generated by Django 4.1.7 on 2023-03-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ticket_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.theme', verbose_name='Тема вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.ticket', verbose_name='Билет'),
        ),
    ]
