# Generated by Django 4.1.7 on 2023-03-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_answer_ques_alter_question_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(db_index=True, default=0, null=True, verbose_name='Билет'),
        ),
    ]
