# Generated by Django 4.1.7 on 2023-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiselect',
            field=models.BooleanField(default=False, verbose_name='Несколько вариантов'),
        ),
    ]
