# Generated by Django 4.1.7 on 2024-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_question_multiselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(db_index=True, max_length=500),
        ),
    ]
