# Generated by Django 4.1.7 on 2024-09-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Вопрос'),
        ),
    ]
